### ISSUE TITLE
error: no member named 'nr' in 'ggml_backend_meta_split_state'

### ISSUE THREAD

**Issue by yurivict** [ggml-org/ggml#1530]
b9553 fails to build with ggml-0.13.1 (latest release):
```
/usr/ports/misc/llama-cpp/work/llama.cpp-b9553/src/llama-model.cpp:670:25: error: no member named 'nr' in 'ggml_backend_meta_split_state'
  670 |             split_state.nr[is] = nr_s;
      |             ~~~~~~~~~~~ ^
/usr/ports/misc/llama-cpp/work/llama.cpp-b9553/src/llama-model.cpp:675:21: error: no member named 'nr' in 'ggml_backend_meta_split_state'
  675 |         split_state.nr[0] = 1;
      |         ~~~~~~~~~~~ ^
2 errors generated.
```

You might say: Use the bundled ggml, but it isn't properly bundled and it installs shared libs and headers of ggml which conflicts with other packages that use standalone ggml. The bundled ggml is not usable in the context of packaging system.

**Comment by ggerganov** [comment]
Should be fixed with latest version
